blank_issues_enabled: false
contact_links:
  - name: "ğŸ› Report a Bug"
    url: https://github.com/T0pcyber/Hawk/issues/new?template=user_bug_report.yml
    about: "Found a bug? Report it here"
  - name: "ğŸ’¡ Suggest a Feature"
    url: https://github.com/T0pcyber/Hawk/issues/new?template=user_feature_request.yml
    about: "Have an idea for improvement? Let us know"
  - name: "ğŸ’¡ Dev Feature Request Form"
    url: https://github.com/T0pcyber/Hawk/issues/new?template=dev_feature_request.yml
    about: "Have an idea for improvement? Let us know"
  - name: "ğŸ“š Documentation Issue"
    url: https://github.com/T0pcyber/Hawk/issues/new?template=documentation.yml
    about: "Report issues with documentation"
