on:
  push:
    branches:
      - master
      - "feature/144-implement-dual-validation-psscriptanalyzer-with-standardized-settings"

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1
      - name: Install Prerequisites
        run: .\build\vsts-prerequisites.ps1
        shell: powershell
      - name: Validate
        run: .\build\vsts-validate.ps1
        shell: powershell
      - name: Build
        run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
        shell: powershell
        env:
          APIKEY: ${{ secrets.ApiKey }}
